[package]
name = "ssh_jumper"
version = "0.1.0"
description = "Async SSH tunnel through a jump host."
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "1.3.1"
async-ssh2-lite = "0.2.1"
async-std-resolver = "0.20.0"
futures = "0.3.13"
ssh_jumper_model = { version = "0.1.0", path = "../ssh_jumper_model" }
tokio = { version = "1.3.0", features = ["rt"] }
